# MATH 210 Introduction to Mathematical Computing

**April 7, 2025**

In [40]:
import numpy as np
import scipy.linalg as la

## Power Method

In [41]:
A = np.array([[1.,1.,0.,0.],[1.,1.,-1,0.],[0.,-1.,1.,1.],[0.,0.,1.,-1.]])
A

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  1., -1.,  0.],
       [ 0., -1.,  1.,  1.],
       [ 0.,  0.,  1., -1.]])

In [42]:
A.shape

(4, 4)

In [43]:
evals,evecs = la.eig(A)

In [44]:
evals.real

array([ 2.49550766,  1.21968687, -0.21968687, -1.49550766])

In [45]:
evecs

array([[ 0.45218222, -0.68391972, -0.56650592,  0.0828016 ],
       [ 0.67624197, -0.15024818,  0.69095983, -0.20663203],
       [-0.55914283, -0.65091217,  0.27624871, -0.4328502 ],
       [-0.15996041, -0.29324504,  0.3540229 ,  0.87354897]])

In [46]:
x0 = np.array([1.,0.,0.,0.,])
x0

array([1., 0., 0., 0.])

In [47]:
x1 = A@x0
x1

array([1., 1., 0., 0.])

In [48]:
x2 = A@x1
x2

array([ 2.,  2., -1.,  0.])

In [49]:
x3 = A@x2
x3

array([ 4.,  5., -3., -1.])

In [50]:
x4 = A@x3
x4

array([ 9., 12., -9., -2.])

In [51]:
lam0 = x3.T@A@x3/(x3.T@x3)
lam0

2.450980392156863

In [52]:
def eigPower(A,N=20):
    n = A.shape[0]
    xk = np.random.rand(n)
    for k in range(N):
        y = A@xk
        xk = y/la.norm(y)
    lam = xk.T@A@xk/(xk.T@xk)
    return (lam, xk)

In [53]:
lam0,v0 = eigPower(A)

In [54]:
lam0

2.495507656527653

In [55]:
v0

array([ 0.45218332,  0.67624317, -0.55913962, -0.15996348])

In [56]:
evals,evecs = la.eig(A)
evals.real[0]

2.4955076566049246

In [57]:
evecs[:,0]

array([ 0.45218222,  0.67624197, -0.55914283, -0.15996041])

In [58]:
B = np.array([[1.,5.],[5.,1.]])
eigPower(B)

(5.999999973553078, array([0.70714314, 0.70707042]))